---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/pbnetwork.com/msp

    - &Org1
        Name: Org1MSP

        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/org1.pbnetwork.com/msp/

        AnchorPeers:
            - Host: peer0.org1.pbnetwork.com
              Port: 7051

    - &Org1Idemix
        Name: idemixMSP1

        ID: idemixMSPID1

        MSPTYPE: idemix

        MSPDIR: crypto-config/peerOrganizations/org1.pbnetwork.com/idemix/

    - &Org2
        Name: Org2MSP

        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/org2.pbnetwork.com/msp/

        AnchorPeers:
            - Host: peer0.org2.pbnetwork.com
              Port: 7051

    - &Org2Idemix
        Name: idemixMSP2

        ID: idemixMSPID2

        MSPTYPE: idemix

        MSPDIR: crypto-config/peerOrganizations/org2.pbnetwork.com/idemix/

    - &Org3
        Name: Org3MSP

        ID: Org3MSP

        MSPDir: crypto-config/peerOrganizations/org3.pbnetwork.com/msp/

        AnchorPeers:
            - Host: peer0.org3.pbnetwork.com
              Port: 7051

    - &Org3Idemix
        Name: idemixMSP3

        ID: idemixMSPID3

        MSPTYPE: idemix

        MSPDIR: crypto-config/peerOrganizations/org3.pbnetwork.com/idemix/

Capabilities:

    Channel: &ChannelCapabilities
        V1_3: true
    
    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.pbnetwork.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

Application: &ApplicationDefaults

    Organizations:
    
    Capabilities:
        <<: *ApplicationCapabilities

Profiles:

    ThreeOrgsOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Org1Idemix
                    - *Org2Idemix
                    - *Org3Idemix
    ThreeOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
                - *Org1Idemix
                - *Org2Idemix
                - *Org3Idemix
            Capabilities:
                <<: *ApplicationCapabilities
