version: '2'

networks:
  onlab:

services:
                                            ######
                                            # CA #
                                            ######
  ca.org1.pbnetwork.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.pbnetwork.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.pbnetwork.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
     # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.pbnetwork.com-cert.pem
     # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.pbnetwork.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key.pem'
    volumes:
      - ./crypto-config/cas/ca.org1.pbnetwork.com/ca/:/etc/hyperledger/fabric-ca-server-config
     # - ../config/crypto-config/peerOrganizations/org1.pbnetwork.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.org1.pbnetwork.com
    networks:
      - onlab

  ca.org2.pbnetwork.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.pbnetwork.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.pbnetwork.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
     # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.pbnetwork.com-cert.pem
     # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
    ports:
      - "7055:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.pbnetwork.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key.pem'
    volumes:
      - ./crypto-config/cas/ca.org2.pbnetwork.com/ca/:/etc/hyperledger/fabric-ca-server-config
     # - ../config/crypto-config/peerOrganizations/org1.pbnetwork.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.org2.pbnetwork.com
    networks:
      - onlab

  ca.org3.pbnetwork.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org3.pbnetwork.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.pbnetwork.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
     # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.pbnetwork.com-cert.pem
     # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
    ports:
      - "7056:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.pbnetwork.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key.pem'
    volumes:
      - ./crypto-config/cas/ca.org3.pbnetwork.com/ca/:/etc/hyperledger/fabric-ca-server-config
     # - ../config/crypto-config/peerOrganizations/org1.pbnetwork.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.org3.pbnetwork.com
    networks:
      - onlab
