#!/bin/bash

export GOPATH=/home/prehoda/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN

docker rm -f $(docker ps -aq)

sudo rm -r $HOME/mycode/onlab/pbnetwork/ca/clients/
sudo rm -r $HOME/mycode/onlab/pbnetwork/ca/tlscacerts
cd $HOME/mycode/onlab/pbnetwork/
sudo rm -r ./channel-artifacts
sudo rm -r ./crypto-config/peerOrganizations/ ./crypto-config/ordererOrganizations/ ./crypto-config/cas/
