#!/bin/bash

export HOME=/home/prehi
export CHANNEL_NAME=mychannel
export GOPATH=$HOME/go
export GOROOT=/opt/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN:$GOROOT/bin

export CACERT_ORDERER=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/pbnetwork.com/orderers/orderer.pbnetwork.com/tls/tlscacerts/tls-localhost-7054.pem
export CACERT_ORG1=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/peers/peer0.org1.pbnetwork.com/tls/tlscacerts/tls-localhost-7054.pem
export CACERT_ORG2=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/peers/peer0.org2.pbnetwork.com/tls/tlscacerts/tls-localhost-7055.pem
export CACERT_ORG3=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/peers/peer0.org3.pbnetwork.com/tls/tlscacerts/tls-localhost-7056.pem

peer channel create -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx --tls --cafile $CACERT_ORDERER

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/users/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG1

peer channel join -b mychannel.block

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/users/Admin@org2.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org2.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org2MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG2

peer channel join -b mychannel.block

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG3

peer channel join -b mychannel.block

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/users/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG1

peer channel update -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org1MSPanchors.tx --tls --cafile $CACERT_ORDERER

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/users/Admin@org2.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org2.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org2MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG2

peer channel update -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org2MSPanchors.tx --tls --cafile $CACERT_ORDERER

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG3

peer channel update -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org3MSPanchors.tx --tls --cafile $CACERT_ORDERER

# Install chaincode to all peers

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/users/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG1

peer chaincode install -n privatedata -v 1.0 -p github.com/chaincode/privatedata

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/users/Admin@org2.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org2.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org2MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG2

peer chaincode install -n privatedata -v 1.0 -p github.com/chaincode/privatedata

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP" CORE_PEER_TLS_ROOTCERT_FILE=$CACERT_ORG3

peer chaincode install -n privatedata -v 1.0 -p github.com/chaincode/privatedata

# Instantiate chaincode

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/users/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP" CORE_PEER_TLS_ROOTCERT_FILE=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/peers/peer0.org1.pbnetwork.com/tls/tlscacerts/tls-localhost-7054.pem

peer chaincode instantiate -o orderer.pbnetwork.com:7050 -C $CHANNEL_NAME -n privatedata -v 1.0 -c '{"Args":["init"]}' -P "OR ('Org1MSP.member','Org2MSP.member','Org3MSP.member')" --collections-config $GOPATH/src/github.com/chaincode/privatedata/collections_config.json --tls --cafile $CACERT_ORG1

