#!/bin/bash

export HOME=/home/prehoda
export CHANNEL_NAME=mychannel
export GOPATH=$HOME/go
export GOROOT=/opt/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN:$GOROOT/bin
peer channel create -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx

peer channel join -b mychannel.block

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/users/Admin@org2.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org2.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org2MSP" peer channel join -b mychannel.block

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP" peer channel join -b mychannel.block

CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users1/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP"

peer channel update -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org1MSPanchors.tx

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/users/Admin@org2.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org2.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org2MSP" peer channel update -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org2MSPanchors.tx

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP" peer channel update -o orderer.pbnetwork.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org3MSPanchors.tx

# Install chaincode to all peers

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/users/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP"

peer chaincode install -n privatedata -v 1.0 -p github.com/chaincode/privatedata

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.pbnetwork.com/users/Admin@org2.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org2.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org2MSP"

peer chaincode install -n privatedata -v 1.0 -p github.com/chaincode/privatedata

CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP"

peer chaincode install -n privatedata -v 1.0 -p github.com/chaincode/privatedata

# Instantiate chaincode

peer chaincode instantiate -o orderer.pbnetwork.com:7050 -C $CHANNEL_NAME -n privatedata -v 1.0 -c '{"Args":["init"]}' -P "OR ('Org1MSP.member','Org2MSP.member','Org3MSP.member')" --collections-config $GOPATH/src/github.com/chaincode/privatedata/collections_config.json

# Invoke

# CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.pbnetwork.com/users/Admin@org1.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org1.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org1MSP"

# peer chaincode invoke -o orderer.pbnetwork.com:7050 -C $CHANNEL_NAME -n privatedata -c '{"Args":["createPen","PEN0","PAX", "Blue", "15 cm", "95 mm", "0.5 mm", "10", "50"]}'

# peer chaincode invoke -o orderer.pbnetwork.com:7050 -C $CHANNEL_NAME -n privatedata -c '{"Args":["getPen","PEN0"]}'

# peer chaincode invoke -o orderer.pbnetwork.com:7050 -C $CHANNEL_NAME -n privatedata -c '{"Args":["getPenPrice","PEN0"]}'

# CORE_PEER_MSPCONFIGPATH=$GOPATH/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.pbnetwork.com/users/Admin@org3.pbnetwork.com/msp CORE_PEER_ADDRESS=peer0.org3.pbnetwork.com:7051 CORE_PEER_LOCALMSPID="Org3MSP"

# peer chaincode invoke -o orderer.pbnetwork.com:7050 -C $CHANNEL_NAME -n privatedata -c '{"Args":["getPenPrice","PEN0"]}'

